In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Former Names

In [2]:
former_names = pd.read_csv(r"..\data\former_names.csv")
former_names.head()

          current                former  start_date    end_date
0           Benin               Dahomey  1959-11-08  1975-11-30
1    Burkina Faso           Upper Volta  1960-04-14  1984-08-04
2         Curaçao  Netherlands Antilles  1957-03-03  2010-10-10
3  Czechoslovakia               Bohemia  1903-04-05  1919-01-01
4  Czechoslovakia   Bohemia and Moravia  1939-01-01  1945-05-01

In [9]:
len(former_names)

36

In [4]:
former_names.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   current     36 non-null     object
 1   former      36 non-null     object
 2   start_date  36 non-null     object
 3   end_date    36 non-null     object
dtypes: object(4)
memory usage: 1.3+ KB

In [8]:
all_former_names = former_names.groupby('current')['former'].apply(list)
print(all_former_names)

current
Benin                                                          [Dahomey]
Burkina Faso                                               [Upper Volta]
Curaçao                                           [Netherlands Antilles]
Czechoslovakia         [Bohemia, Bohemia and Moravia, Representation ...
DR Congo               [Belgian Congo, Congo-Léopoldville, Congo-Kins...
Djibouti                                             [French Somaliland]
Egypt                                             [United Arab Republic]
Eswatini                                                     [Swaziland]
Ghana                                                       [Gold Coast]
Guinea-Bissau                                        [Portuguese Guinea]
Guyana                                                  [British Guiana]
Indonesia                                            [Dutch East Indies]
Israel                                             [Mandatory Palestine]
Malawi                                                       [Nyasaland]
Malaysia                                                        [Malaya]
Myanmar                                                          [Burma]
North Macedonia                                              [Macedonia]
Northern Ireland                                               [Ireland]
Republic of Ireland                             [Irish Free State, Éire]
Russia                                               [Soviet Union, CIS]
Samoa                                                    [Western Samoa]
Serbia                            [FR Yugoslavia, Serbia and Montenegro]
Sri Lanka                                                       [Ceylon]
Suriname                                                  [Dutch Guyana]
Tanzania                                                    [Tanganyika]
Vanuatu                                                   [New Hebrides]
Zambia                                               [Northern Rhodesia]
Zimbabwe                                             [Southern Rhodesia]
Name: former, dtype: object

## Results

In [23]:
results = pd.read_csv(r"..\data\results.csv")
results.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [25]:
results['date'] = pd.to_datetime(results['date'], format='%Y-%m-%d')

In [26]:
results.describe()

                                date    home_score    away_score
count                          49477  49453.000000  49453.000000
mean   1994-05-22 13:38:00.550558720      1.757467      1.181708
min              1872-11-30 00:00:00      0.000000      0.000000
25%              1980-09-09 00:00:00      1.000000      0.000000
50%              2000-07-15 00:00:00      1.000000      1.000000
75%              2013-07-15 00:00:00      2.000000      2.000000
max              2026-06-27 00:00:00     31.000000     21.000000
std                              NaN      1.774250      1.401770

In [28]:
rows_with_na = results[results.isna().any(axis=1)]
rows_with_na

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49453,2026-06-24,Mexico,Czech Republic,NaN,NaN,FIFA World Cup,Mexico City,Mexico,False
49454,2026-06-24,South Africa,South Korea,NaN,NaN,FIFA World Cup,Guadalupe,Mexico,True
49455,2026-06-24,Canada,Switzerland,NaN,NaN,FIFA World Cup,Vancouver,Canada,False
49456,2026-06-24,Bosnia and Herzegovina,Qatar,NaN,NaN,FIFA World Cup,Seattle,United States,True
49457,2026-06-24,Scotland,Brazil,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49458,2026-06-24,Morocco,Haiti,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49459,2026-06-25,United States,Turkey,NaN,NaN,FIFA World Cup,Inglewood,United States,False
49460,2026-06-25,Paraguay,Australia,NaN,NaN,FIFA World Cup,Santa Clara,United States,True
49461,2026-06-25,Curaçao,Ivory Coast,NaN,NaN,FIFA World Cup,Philadelphia,United States,True
49462,2026-06-25,Ecuador,Germany,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49463,2026-06-25,Japan,Sweden,NaN,NaN,FIFA World Cup,Arlington,United States,True
49464,2026-06-25,Tunisia,Netherlands,NaN,NaN,FIFA World Cup,Kansas City,United States,True
49465,2026-06-26,Egypt,Iran,NaN,NaN,FIFA World Cup,Seattle,United States,True
49466,2026-06-26,New Zealand,Belgium,NaN,NaN,FIFA World Cup,Vancouver,Canada,True
49467,2026-06-26,Cape Verde,Saudi Arabia,NaN,NaN,FIFA World Cup,Houston,United States,True
49468,2026-06-26,Uruguay,Spain,NaN,NaN,FIFA World Cup,Zapopan,Mexico,True
49469,2026-06-26,Norway,France,NaN,NaN,FIFA World Cup,Foxborough,United States,True
49470,2026-06-26,Senegal,Iraq,NaN,NaN,FIFA World Cup,Toronto,Canada,True
49471,2026-06-27,Algeria,Austria,NaN,NaN,FIFA World Cup,Kansas City,United States,True
49472,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49473,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49474,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49475,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49476,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

In [29]:
# ===================================================================
# ============== updating world cup group stage scores ============== 
# ===================================================================

# Mexico vs Czech Republic 3-0
results.loc[49453, 'home_score'] = 3
results.loc[49453, 'away_score'] = 0

# South Africa vs South Korea 1-0
results.loc[49454, 'home_score'] = 1
results.loc[49454, 'away_score'] = 0

# Canada vs Switzerland 1-2
results.loc[49455, 'home_score'] = 1
results.loc[49455, 'away_score'] = 2

# Bosnia and Herzegovina vs Qatar 3-1
results.loc[49456, 'home_score'] = 3
results.loc[49456, 'away_score'] = 1

# Scotland vs Brazil 0-3
results.loc[49457, 'home_score'] = 0
results.loc[49457, 'away_score'] = 3

# Morocco vs Haiti 4-2
results.loc[49458, 'home_score'] = 4
results.loc[49458, 'away_score'] = 2

# United States vs Turkey 3-2
results.loc[49459, 'home_score'] = 3
results.loc[49459, 'away_score'] = 2

# Paraguay vs Australia 0-0
results.loc[49460, 'home_score'] = 0
results.loc[49460, 'away_score'] = 0

# Curaçao vs Ivory Coast 0-2
results.loc[49461, 'home_score'] = 0
results.loc[49461, 'away_score'] = 2

# Ecuador vs Germany 2-1
results.loc[49462, 'home_score'] = 2
results.loc[49462, 'away_score'] = 1

# Japan vs Sweden 1-1
results.loc[49463, 'home_score'] = 1
results.loc[49463, 'away_score'] = 1

# Tunisia vs Netherlands 1-3
results.loc[49464, 'home_score'] = 1
results.loc[49464, 'away_score'] = 3

# Egypt vs Iran 1-1
results.loc[49465, 'home_score'] = 1
results.loc[49465, 'away_score'] = 1

# New Zealand vs Belgium 1-5
results.loc[49466, 'home_score'] = 1
results.loc[49466, 'away_score'] = 5

# Cape Verde vs Saudi Arabia 0-0
results.loc[49467, 'home_score'] = 0
results.loc[49467, 'away_score'] = 0

# Uruguay vs Spain 0-1
results.loc[49468, 'home_score'] = 0
results.loc[49468, 'away_score'] = 1

# Norway vs France 1-4
results.loc[49469, 'home_score'] = 1
results.loc[49469, 'away_score'] = 4

# Senegal vs Iraq 5-0
results.loc[49470, 'home_score'] = 5
results.loc[49470, 'away_score'] = 0


# ===================================================================
# ================= need to update once games finish ================ 
# ===================================================================

# # Algeria vs Austria 
# results.loc[49471, 'home_score'] = 
# results.loc[49471, 'away_score'] = 

# # Jordan vs Argentina 
# results.loc[49472, 'home_score'] = 
# results.loc[49472, 'away_score'] = 

# Colombia vs Portugal 
# results.loc[49473, 'home_score'] = 
# results.loc[49473, 'away_score'] = 

# DR Congo vs Uzbekistan 
# results.loc[49474, 'home_score'] = 
# results.loc[49474, 'away_score'] = 

# # Panama vs England 
# results.loc[49475, 'home_score'] = 
# results.loc[49475, 'away_score'] = 

# # Croatia vs Ghana 
# results.loc[49476, 'home_score'] = 
# results.loc[49476, 'away_score'] =

In [30]:
rows_with_na = results[results.isna().any(axis=1)]
rows_with_na

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49471,2026-06-27,Algeria,Austria,NaN,NaN,FIFA World Cup,Kansas City,United States,True
49472,2026-06-27,Jordan,Argentina,NaN,NaN,FIFA World Cup,Arlington,United States,True
49473,2026-06-27,Colombia,Portugal,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49474,2026-06-27,DR Congo,Uzbekistan,NaN,NaN,FIFA World Cup,Atlanta,United States,True
49475,2026-06-27,Panama,England,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49476,2026-06-27,Croatia,Ghana,NaN,NaN,FIFA World Cup,Philadelphia,United States,True

## Shootouts

In [11]:
shootouts = pd.read_csv(r"..\data\shootouts.csv")
shootouts.head()

         date    home_team         away_team       winner first_shooter
0  1967-08-22        India            Taiwan       Taiwan           NaN
1  1971-11-14  South Korea  Vietnam Republic  South Korea           NaN
2  1972-05-07  South Korea              Iraq         Iraq           NaN
3  1972-05-17     Thailand       South Korea  South Korea           NaN
4  1972-05-19     Thailand          Cambodia     Thailand           NaN

In [32]:
shootouts['date'] = pd.to_datetime(shootouts['date'], format='%Y-%m-%d')

In [33]:
shootouts.describe()

                                date
count                            678
mean   2004-03-16 13:54:41.415929088
min              1967-08-22 00:00:00
25%              1993-01-30 00:00:00
50%              2004-06-25 00:00:00
75%              2017-06-23 12:00:00
max              2026-06-06 00:00:00

## Goal Scorers

In [12]:
goal_scorers = pd.read_csv(r"..\data\goalscorers.csv")
goal_scorers.head()

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
0,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,44.0,False,False
1,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,55.0,False,False
2,1916-07-02,Chile,Uruguay,Uruguay,Isabelino Gradín,70.0,False,False
3,1916-07-02,Chile,Uruguay,Uruguay,José Piendibene,75.0,False,False
4,1916-07-06,Argentina,Chile,Argentina,Alberto Ohaco,2.0,False,False

In [34]:
goal_scorers['date'] = pd.to_datetime(goal_scorers['date'], format='%Y-%m-%d')

In [35]:
goal_scorers.describe()

                                date        minute
count                          47747  47493.000000
mean   1999-05-15 13:27:06.849854464     50.053229
min              1916-07-02 00:00:00      1.000000
25%              1989-03-15 00:00:00     28.000000
50%              2004-06-16 00:00:00     51.000000
75%              2016-06-10 00:00:00     73.000000
max              2026-06-23 00:00:00    122.000000
std                              NaN     26.365695

In [31]:
scorer_rows_with_na = goal_scorers[goal_scorers.isna().any(axis=1)]
scorer_rows_with_na

,date,home_team,away_team,team,scorer,minute,own_goal,penalty
3347,1960-10-16,Taiwan,Vietnam Republic,Taiwan,Yiu Cheuk Yin,NaN,False,False
4059,1963-11-26,Ghana,Ethiopia,Ghana,Edward Acquah,NaN,False,False
4060,1963-11-26,Ghana,Ethiopia,Ghana,Edward Acquah,NaN,False,False
4063,1963-11-28,Ethiopia,Tunisia,Ethiopia,Mengistu Worku,NaN,False,False
4064,1963-11-28,Ethiopia,Tunisia,Ethiopia,Mengistu Worku,NaN,False,False
...,...,...,...,...,...,...,...,...
16812,1997-03-27,Saudi Arabia,Bangladesh,Saudi Arabia,Abdullah Al-Dosari,NaN,False,False
16838,1997-03-29,Taiwan,Bangladesh,Taiwan,Hsu Te Ming,NaN,False,False
16839,1997-03-29,Taiwan,Bangladesh,Bangladesh,Alfaz Ahmed,NaN,False,False
16840,1997-03-29,Taiwan,Bangladesh,Bangladesh,Imtiaz Ahmed Nakib,NaN,False,False
16849,1997-03-31,Bangladesh,Malaysia,Malaysia,Zainal Abidin Hassan,NaN,False,False

In [ ]:
# Mexico vs Czech Republic 3-0
new_data = pd.DataFrame([
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Mexico',
    'away_team': 'Czech Republic',
    'team': 'Mexico',
    'scorer': 'Mateo Chávez',
    'minute': 55,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Mexico',
    'away_team': 'Czech Republic',
    'team': 'Mexico',
    'scorer': 'Julián Quiñones',
    'minute': 61,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Mexico',
    'away_team': 'Czech Republic',
    'team': 'Mexico',
    'scorer': 'Álvaro Fidalgo',
    'minute': 94,
    'own_goal': False,
    'penalty': False,
}
])

# South Africa vs South Korea 1-0
RSA_vs_KOR = [
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'South Africa',
    'away_team': 'South Korea',
    'team': 'South Africa',
    'scorer': 'Thapelo Maseko',
    'minute': 63,
    'own_goal': False,
    'penalty': False,
}
]
new_data = pd.concat([new_data, RSA_vs_KOR], ignore_index=True)

# Canada vs Switzerland 1-2
CAN_vs_SUI = [
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Canada',
    'away_team': 'Switzerland',
    'team': 'Switzerland',
    'scorer': 'Rubén Vargas',
    'minute': 46,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Canada',
    'away_team': 'Switzerland',
    'team': 'Switzerland',
    'scorer': 'Johan Manzambi',
    'minute': 57,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Canada',
    'away_team': 'Switzerland',
    'team': 'Canada',
    'scorer': 'Promise David',
    'minute': 76,
    'own_goal': False,
    'penalty': False,
}
]
new_data = pd.concat([new_data, CAN_vs_SUI], ignore_index=True)

# Bosnia and Herzegovina vs Qatar 3-1
BIH_vs_QAT = [
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Bosnia and Herzegovina',
    'away_team': 'Qatar',
    'team': 'Bosnia and Herzegovina',
    'scorer': 'Kerim Alajbegović',
    'minute': 29,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Bosnia and Herzegovina',
    'away_team': 'Qatar',
    'team': 'Bosnia and Herzegovina',
    'scorer': 'Mahmud Abunada',
    'minute': 34,
    'own_goal': True,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Bosnia and Herzegovina',
    'away_team': 'Qatar',
    'team': 'Qatar',
    'scorer': 'Hassan Al-Haydos',
    'minute': 42,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Bosnia and Herzegovina',
    'away_team': 'Qatar',
    'team': 'Bosnia and Herzegovina',
    'scorer': 'Ermin Mahmić',
    'minute': 80,
    'own_goal': False,
    'penalty': False,
}
]
new_data = pd.concat([new_data, BIH_vs_QAT], ignore_index=True)

# Scotland vs Brazil 0-3
SCO_vs_BRA = [
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Scotland',
    'away_team': 'Brazil',
    'team': 'Brazil',
    'scorer': 'Vinícius Júnior',
    'minute': 7,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Scotland',
    'away_team': 'Brazil',
    'team': 'Brazil',
    'scorer': 'Vinícius Júnior',
    'minute': 48,
    'own_goal': True,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Scotland',
    'away_team': 'Brazil',
    'team': 'Brazil',
    'scorer': 'Matheus Cunha',
    'minute': 60,
    'own_goal': False,
    'penalty': False,
}
]
new_data = pd.concat([new_data, SCO_vs_BRA], ignore_index=True)

# Morocco vs Haiti 4-2
MAR_vs_HAI = [
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Morocco',
    'away_team': 'Haiti',
    'team': 'Haiti',
    'scorer': 'Yassine Bounou',
    'minute': 10,
    'own_goal': True,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Morocco',
    'away_team': 'Haiti',
    'team': 'Morocco',
    'scorer': 'Achraf Hakimi',
    'minute': 39,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Morocco',
    'away_team': 'Haiti',
    'team': 'Haiti',
    'scorer': 'Wilson Isidor',
    'minute': 43,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Morocco',
    'away_team': 'Haiti',
    'team': 'Morocco',
    'scorer': 'Ismael Saibari',
    'minute': 46,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Morocco',
    'away_team': 'Haiti',
    'team': 'Morocco',
    'scorer': 'Soufiane Rahimi',
    'minute': 78,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-24', format='%Y-%m-%d'),
    'home_team': 'Morocco',
    'away_team': 'Haiti',
    'team': 'Morocco',
    'scorer': 'Gessime Yassine',
    'minute': 89,
    'own_goal': False,
    'penalty': False,
}
]
new_data = pd.concat([new_data, MAR_vs_HAI], ignore_index=True)

# United States vs Turkey 3-2
USA_vs_TUR = [
    {
    'date': pd.to_datetime('2026-06-25', format='%Y-%m-%d'),
    'home_team': 'United States',
    'away_team': 'Turkey',
    'team': 'United States',
    'scorer': 'Auston Trusty',
    'minute': 3,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-25', format='%Y-%m-%d'),
    'home_team': 'United States',
    'away_team': 'Turkey',
    'team': 'Turkey',
    'scorer': 'Arda Güler',
    'minute': 10,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-25', format='%Y-%m-%d'),
    'home_team': 'United States',
    'away_team': 'Turkey',
    'team': 'Turkey',
    'scorer': 'Barış Alper Yılmaz',
    'minute': 31,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-25', format='%Y-%m-%d'),
    'home_team': 'United States',
    'away_team': 'Turkey',
    'team': 'United States',
    'scorer': 'Sebastian Berhalter',
    'minute': 49,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-25', format='%Y-%m-%d'),
    'home_team': 'United States',
    'away_team': 'Turkey',
    'team': 'Turkey',
    'scorer': 'Kaan Ayhan',
    'minute': 98,
    'own_goal': False,
    'penalty': False,
}
]
new_data = pd.concat([new_data, USA_vs_TUR], ignore_index=True)

# Paraguay vs Australia 0-0
# No data to fill 

# Curaçao vs Ivory Coast 0-2
CUW_vs_CIV = [
    {
    'date': pd.to_datetime('2026-06-25', format='%Y-%m-%d'),
    'home_team': 'Curaçao',
    'away_team': 'Ivory Coast',
    'team': 'Ivory Coast',
    'scorer': 'Nicolas Pépé',
    'minute': 7,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-25', format='%Y-%m-%d'),
    'home_team': 'Curaçao',
    'away_team': 'Ivory Coast',
    'team': 'Ivory Coast',
    'scorer': 'Nicolas Pépé',
    'minute': 64,
    'own_goal': False,
    'penalty': False,
}
]
new_data = pd.concat([new_data, CUW_vs_CIV], ignore_index=True)

# Ecuador vs Germany 2-1
ECU_vs_GER = [
    {
    'date': pd.to_datetime('2026-06-25', format='%Y-%m-%d'),
    'home_team': 'Ecuador',
    'away_team': 'Germany',
    'team': 'Germany',
    'scorer': 'Leroy Sané',
    'minute': 2,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-25', format='%Y-%m-%d'),
    'home_team': 'Ecuador',
    'away_team': 'Germany',
    'team': 'Ecuador',
    'scorer': 'Nilson Angulo',
    'minute': 9,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-25', format='%Y-%m-%d'),
    'home_team': 'Ecuador',
    'away_team': 'Germany',
    'team': 'Ecuador',
    'scorer': 'Gonzalo Plata',
    'minute': 77,
    'own_goal': False,
    'penalty': False,
}
]
new_data = pd.concat([new_data, ECU_vs_GER], ignore_index=True)

# Japan vs Sweden 1-1
JPN_vs_SWE = [
    {
    'date': pd.to_datetime('2026-06-25', format='%Y-%m-%d'),
    'home_team': 'Japan',
    'away_team': 'Sweden',
    'team': 'Japan',
    'scorer': 'Daizen Maeda',
    'minute': 56,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-25', format='%Y-%m-%d'),
    'home_team': 'Japan',
    'away_team': 'Sweden',
    'team': 'Sweden',
    'scorer': 'Anthony Elanga',
    'minute': 62,
    'own_goal': False,
    'penalty': False,
}
]
new_data = pd.concat([new_data, JPN_vs_SWE], ignore_index=True)

# Tunisia vs Netherlands 1-3
TUN_vs_NED = [
    {
    'date': pd.to_datetime('2026-06-25', format='%Y-%m-%d'),
    'home_team': 'Tunisia',
    'away_team': 'Netherlands',
    'team': 'Netherlands',
    'scorer': 'Ellyes Skhiri',
    'minute': 3,
    'own_goal': True,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-25', format='%Y-%m-%d'),
    'home_team': 'Tunisia',
    'away_team': 'Netherlands',
    'team': 'Netherlands',
    'scorer': 'Brian Brobbey',
    'minute': 7,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-25', format='%Y-%m-%d'),
    'home_team': 'Tunisia',
    'away_team': 'Netherlands',
    'team': 'Tunisia',
    'scorer': 'Hazem Mastouri',
    'minute': 54,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-25', format='%Y-%m-%d'),
    'home_team': 'Tunisia',
    'away_team': 'Netherlands',
    'team': 'Netherlands',
    'scorer': 'Jan Paul van Hecke',
    'minute': 62,
    'own_goal': False,
    'penalty': False,
}
]
new_data = pd.concat([new_data, TUN_vs_NED], ignore_index=True)

# Egypt vs Iran 1-1
EGY_vs_IRN = [
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'Egypt',
    'away_team': 'Iran',
    'team': 'Egypt',
    'scorer': 'Mahmoud Saber',
    'minute': 5,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'Egypt',
    'away_team': 'Iran',
    'team': 'Iran',
    'scorer': 'Ramin Rezaeian',
    'minute': 14,
    'own_goal': False,
    'penalty': False,
}
]
new_data = pd.concat([new_data, EGY_vs_IRN], ignore_index=True)

# New Zealand vs Belgium 1-5
NZL_vs_BEL = [
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'New Zealand',
    'away_team': 'Belgium',
    'team': 'Belgium',
    'scorer': 'Leandro Trossard',
    'minute': 28,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'New Zealand',
    'away_team': 'Belgium',
    'team': 'Belgium',
    'scorer': 'Leandro Trossard',
    'minute': 50,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'New Zealand',
    'away_team': 'Belgium',
    'team': 'Belgium',
    'scorer': 'Kevin De Bruyne',
    'minute': 66,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'New Zealand',
    'away_team': 'Belgium',
    'team': 'New Zealand',
    'scorer': 'Elijah Just',
    'minute': 84,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'New Zealand',
    'away_team': 'Belgium',
    'team': 'Belgium',
    'scorer': 'Romelu Lukaku',
    'minute': 86,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'New Zealand',
    'away_team': 'Belgium',
    'team': 'Belgium',
    'scorer': 'Alexis Saelemaekers',
    'minute': 94,
    'own_goal': False,
    'penalty': False,
}
]
new_data = pd.concat([new_data, NZL_vs_BEL], ignore_index=True)

# Cape Verde vs Saudi Arabia 0-0
# No data to fill

# Uruguay vs Spain 0-1
URU_vs_ESP = [
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'Uruguay',
    'away_team': 'Spain',
    'team': 'Spain',
    'scorer': 'Álex Baena',
    'minute': 42,
    'own_goal': False,
    'penalty': False,
}
]
new_data = pd.concat([new_data, URU_vs_ESP], ignore_index=True)

# Norway vs France 1-4
NOR_vs_FRA = [
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'Norway',
    'away_team': 'France',
    'team': 'France',
    'scorer': 'Ousmane Dembélé',
    'minute': 7,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'Norway',
    'away_team': 'France',
    'team': 'France',
    'scorer': 'Ousmane Dembélé',
    'minute': 20,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'Norway',
    'away_team': 'France',
    'team': 'Norway',
    'scorer': 'Thelo Aasgaard',
    'minute': 21,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'Norway',
    'away_team': 'France',
    'team': 'France',
    'scorer': 'Ousmane Dembélé',
    'minute': 32,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'Norway',
    'away_team': 'France',
    'team': 'France',
    'scorer': 'Désiré Doué',
    'minute': 94,
    'own_goal': False,
    'penalty': False,
}
]
new_data = pd.concat([new_data, NOR_vs_FRA], ignore_index=True)

# Senegal vs Iraq 5-0
SEN_vs_IRQ = [
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'Senegal',
    'away_team': 'Iraq',
    'team': 'Senegal',
    'scorer': 'Habib Diarra',
    'minute': 4,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'Senegal',
    'away_team': 'Iraq',
    'team': 'Senegal',
    'scorer': 'Ismaïla Sarr',
    'minute': 56,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'Senegal',
    'away_team': 'Iraq',
    'team': 'Senegal',
    'scorer': 'Pape Gueye',
    'minute': 59,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'Senegal',
    'away_team': 'Iraq',
    'team': 'Senegal',
    'scorer': 'Pape Gueye',
    'minute': 71,
    'own_goal': False,
    'penalty': False,
},
    {
    'date': pd.to_datetime('2026-06-26', format='%Y-%m-%d'),
    'home_team': 'Senegal',
    'away_team': 'Iraq',
    'team': 'Senegal',
    'scorer': 'Iliman Ndiaye',
    'minute': 82,
    'own_goal': False,
    'penalty': False,
}
]
new_data = pd.concat([new_data, SEN_vs_IRQ], ignore_index=True)


# # Algeria vs Austria 


# # Jordan vs Argentina 


# Colombia vs Portugal 


# DR Congo vs Uzbekistan 


# # Panama vs England 


# # Croatia vs Ghana